def reverse_hash(encryped_string):
    """
    This function decrypt the hashed number generated by the hashed function
    """
    letters = 'acdegilmnoprstuw'
    y = encryped_string
    l = list() # Empty list
    l.append(encryped_string)
    output = ''
    while y/259 >= 7:
        y = y/37
        l.append(y)
    first_character = l[len(l)-1] - 259
    try:
        l.reverse()
        output = output + letters[first_character]
        for m in range(0, len(l)-1):
            output = output+letters[l[m+1] - l[m]*37]
        return output
    except (IndexError, TypeError):
        return 'Not a valid hash number'


